use oficinamecanica;

INSERT INTO Serviços (Descrição, Preço, Status, Categoria)
VALUES
('Troca de óleo de motor', 150.00, 'ativo', 'Manutenção'),
('Alinhamento e balanceamento', 120.00, 'ativo', 'Suspensão'),
('Troca de pastilhas de freio', 180.00, 'ativo', 'Freios'),
('Troca de filtros de ar', 80.00, 'ativo', 'Manutenção'),
('Reparo de motor', 800.00, 'ativo', 'Mecânica'),
('Troca de bateria', 200.00, 'ativo', 'Elétrica'),
('Verificação e troca de velas de ignição', 100.00, 'ativo', 'Mecânica'),
('Substituição de correia dentada', 350.00, 'ativo', 'Mecânica'),
('Reparo de suspensão', 250.00, 'ativo', 'Suspensão'),
('Instalação de sistema de som', 300.00, 'ativo', 'Acessórios'),
('Troca de pneus', 400.00, 'ativo', 'Pneus'),
('Lavagem completa do veículo', 90.00, 'ativo', 'Estética'),
('Troca de embreagem', 600.00, 'ativo', 'Mecânica'),
('Reparo de ar-condicionado', 450.00, 'ativo', 'Elétrica'),
('Instalação de faróis de LED', 220.00, 'ativo', 'Acessórios'),
('Revisão de freios', 150.00, 'ativo', 'Freios'),
('Troca de óleo de transmissão', 200.00, 'ativo', 'Transmissão'),
('Inspeção de sistema de escapamento', 120.00, 'ativo', 'Exaustão'),
('Substituição de coxins de motor', 180.00, 'ativo', 'Mecânica'),
('Troca de amortecedores', 350.00, 'ativo', 'Suspensão'),
('Ajuste de alinhamento de rodas', 100.00, 'ativo', 'Suspensão'),
('Verificação do sistema de injeção eletrônica', 250.00, 'ativo', 'Mecânica'),
('Instalação de kit de rebaixamento', 500.00, 'ativo', 'Acessórios'),
('Reparo de câmbio', 900.00, 'ativo', 'Transmissão'),
('Troca de sensor de estacionamento', 150.00, 'ativo', 'Eletrônica'),
('Manutenção preventiva', 250.00, 'ativo', 'Manutenção'),
('Troca de lâmpadas de faróis', 80.00, 'ativo', 'Elétrica'),
('Reparo de direção hidráulica', 350.00, 'ativo', 'Direção'),
('Alinhamento de direção', 120.00, 'ativo', 'Direção'),
('Instalação de câmera de ré', 220.00, 'ativo', 'Acessórios'),
('Troca de retentor de motor', 280.00, 'ativo', 'Mecânica'),
('Substituição de radiador', 400.00, 'ativo', 'Arrefecimento'),
('Troca de vela de ignição', 50.00, 'ativo', 'Mecânica'),
('Revisão de transmissão', 700.00, 'ativo', 'Transmissão'),
('Ajuste de embreagem', 180.00, 'ativo', 'Mecânica'),
('Instalação de sensor de pressão dos pneus', 150.00, 'ativo', 'Elétrica'),
('Reparo de farol dianteiro', 130.00, 'ativo', 'Estética'),
('Troca de bomba de combustível', 300.00, 'ativo', 'Combustível'),
('Substituição de bomba de direção hidráulica', 400.00, 'ativo', 'Direção'),
('Troca de mangueiras de arrefecimento', 200.00, 'ativo', 'Arrefecimento'),
('Ajuste de motor', 500.00, 'ativo', 'Mecânica'),
('Instalação de alarme automotivo', 350.00, 'ativo', 'Acessórios'),
('Troca de rolamentos de roda', 250.00, 'ativo', 'Suspensão'),
('Inspeção de sistema elétrico', 150.00, 'ativo', 'Elétrica'),
('Reparo de ignição', 250.00, 'ativo', 'Mecânica');

select * from serviços;